"""initialisation table validation

Revision ID: 0acf74159dbb
Revises: f7fa005fbd69
Create Date: 2025-03-26 01:50:55.446432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acf74159dbb'
down_revision = 'f7fa005fbd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('status_validation', sa.String(length=50), nullable=False),
    sa.Column('id_demande', sa.Integer(), nullable=False),
    sa.Column('date_validation', sa.String(length=100), nullable=False),
    sa.Column('notification', sa.String(length=250), nullable=False),
    sa.Column('signature_responsable', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_demande'], ['demande.id'], ),
    sa.ForeignKeyConstraint(['tel_user'], ['user.tel_user'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_demande')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation')
    # ### end Alembic commands ###
