"""ajout cle etrangere dans le table demande

Revision ID: 4ab91797cf18
Revises: 24b80328220d
Create Date: 2025-03-26 17:10:34.884538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab91797cf18'
down_revision = '24b80328220d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_article', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'article', ['id_article'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_article')

    # ### end Alembic commands ###
