"""Initial migration

Revision ID: 9a80e3cc4b5f
Revises: 
Create Date: 2025-03-24 22:03:35.781769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a80e3cc4b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('nom_user', sa.String(length=50), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('role_user', sa.String(length=100), nullable=False),
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_user'),
    sa.UniqueConstraint('mot_de_passe'),
    sa.UniqueConstraint('nom_user'),
    sa.UniqueConstraint('photo'),
    sa.UniqueConstraint('role_user'),
    sa.UniqueConstraint('tel_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
