"""ajout table blacklistetoken pour gerer la token

Revision ID: c35e06058e4c
Revises: 9a80e3cc4b5f
Create Date: 2025-03-25 08:48:30.412822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35e06058e4c'
down_revision = '9a80e3cc4b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_mot_de_passe_key', type_='unique')
        batch_op.drop_constraint('user_nom_user_key', type_='unique')
        batch_op.drop_constraint('user_photo_key', type_='unique')
        batch_op.drop_constraint('user_role_user_key', type_='unique')
        batch_op.drop_constraint('user_tel_user_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('user_tel_user_key', ['tel_user'])
        batch_op.create_unique_constraint('user_role_user_key', ['role_user'])
        batch_op.create_unique_constraint('user_photo_key', ['photo'])
        batch_op.create_unique_constraint('user_nom_user_key', ['nom_user'])
        batch_op.create_unique_constraint('user_mot_de_passe_key', ['mot_de_passe'])

    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
