"""début

Revision ID: e5c7382ba112
Revises: 
Create Date: 2025-03-27 10:17:54.349180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c7382ba112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('nom_user', sa.String(length=50), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('role_user', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=500), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tel_user'),
    sa.UniqueConstraint('email_user'),
    sa.UniqueConstraint('tel_user')
    )
    op.create_table('demande',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('id_article', sa.Integer(), nullable=False),
    sa.Column('status_demande', sa.String(length=50), nullable=False),
    sa.Column('justification_demande', sa.Text(), nullable=False),
    sa.Column('quantite_demande', sa.String(length=100), nullable=False),
    sa.Column('notification_demande', sa.Text(), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tel_user'], ['user.tel_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('type_notification', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_notification', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tel_user'], ['user.tel_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('status_validation', sa.String(length=50), nullable=False),
    sa.Column('id_demande', sa.Integer(), nullable=False),
    sa.Column('date_validation', sa.String(length=100), nullable=False),
    sa.Column('notification', sa.String(length=250), nullable=False),
    sa.Column('signature_responsable', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_demande'], ['demande.id'], ),
    sa.ForeignKeyConstraint(['tel_user'], ['user.tel_user'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_demande')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation')
    op.drop_table('notification')
    op.drop_table('demande')
    op.drop_table('user')
    op.drop_table('blacklist_token')
    op.drop_table('article')
    # ### end Alembic commands ###
