"""ajouter table notification

Revision ID: f7fa005fbd69
Revises: c4a38ae253d4
Create Date: 2025-03-26 01:38:05.573268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fa005fbd69'
down_revision = 'c4a38ae253d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tel_user', sa.String(length=100), nullable=False),
    sa.Column('type_notification', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_notification', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tel_user'], ['user.tel_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('validation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tel_user', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status_validation', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id_demande', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_validation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('notification', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('signature_responsable', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_demande'], ['demande.id'], name='validation_id_demande_fkey'),
    sa.ForeignKeyConstraint(['tel_user'], ['user.tel_user'], name='validation_tel_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='validation_pkey'),
    sa.UniqueConstraint('id_demande', name='validation_id_demande_key')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###
